import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

/**
 * Database Schema for Price Radar
 *
 * This schema defines three main tables:
 * - users: User accounts and subscription plans
 * - monitors: User-created monitoring queries
 * - offers: Deals found by the scraper
 */

export default defineSchema({
  // ============================================
  // USERS TABLE
  // ============================================
  users: defineTable({
    // User profile
    name: v.string(),
    email: v.string(),

    // Subscription plan: 'free' or 'pro'
    plan: v.union(v.literal('free'), v.literal('pro')),

    // Autumn payment integration
    autumnCustomerId: v.optional(v.string()),

    // Metadata
    createdAt: v.number(), // timestamp
    updatedAt: v.number(), // timestamp
  })
    .index('by_email', ['email'])
    .index('by_autumnCustomerId', ['autumnCustomerId']),

  // ============================================
  // MONITORS TABLE
  // ============================================
  monitors: defineTable({
    // Ownership
    userId: v.id('users'),

    // Query details
    queryText: v.string(), // Original user input: "RTX 4080 usata < 800€"
    queryJson: v.any(), // Parsed by AI: { item: "RTX 4080", condition: "used", price_max: 800 }

    // Status: 'active', 'paused', 'error'
    status: v.string(),

    // Scraping configuration
    sites: v.array(v.string()), // ['ebay', 'subito', 'amazon']
    frequencyMinutes: v.number(), // 30 for Free, 3 for Pro

    // Tracking
    lastRunAt: v.optional(v.number()), // Last scraping execution timestamp
    lastErrorAt: v.optional(v.number()), // Last error timestamp
    lastErrorMessage: v.optional(v.string()), // Last error details

    // Metadata
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_userId', ['userId'])
    .index('by_status', ['status'])
    .index('by_userId_status', ['userId', 'status']),

  // ============================================
  // OFFERS TABLE
  // ============================================
  offers: defineTable({
    // Relationships
    monitorId: v.id('monitors'),
    userId: v.id('users'), // Denormalized for faster queries

    // Offer details
    title: v.string(),
    price: v.number(),
    currency: v.string(), // 'EUR', 'USD', etc.
    url: v.string(), // Direct link to the offer

    // Source
    siteName: v.string(), // 'ebay.it', 'subito.it', etc.

    // AI-generated content
    snippet: v.string(), // Short summary generated by AI

    // Optional fields
    imageUrl: v.optional(v.string()),
    condition: v.optional(v.string()), // 'new', 'used', 'refurbished'
    location: v.optional(v.string()), // Seller location

    // Status: 'new', 'archived', 'clicked'
    status: v.string(),

    // Metadata
    foundAt: v.number(), // When the offer was discovered
    archivedAt: v.optional(v.number()), // When user archived it
    clickedAt: v.optional(v.number()), // When user clicked "View Offer"
  })
    .index('by_monitorId', ['monitorId'])
    .index('by_userId', ['userId'])
    .index('by_userId_status', ['userId', 'status'])
    .index('by_status_foundAt', ['status', 'foundAt']) // For sorting new offers
    .index('by_url', ['url']), // For deduplication
})
